### ISSUE TITLE
Random Issues with 0.1.1-alpha

### ISSUE THREAD

**Issue by AlexDoesAThing11** [IanSmith44/Better-Halo-Infinite#1]
Add a Killzone below the map
Shooting the gun please
where did the master chief model go?
Add Sex

**Comment by IanSmith44** [comment]
Killzone will be added next release, so will shooting the gun.
The master chief model was used as the player for a bit but got removed due to technical difficulties
No I will not add Sex

**Comment by IanSmith44** [comment]
ok, secret cutscene sex

**Comment by AlexDoesAThing11** [comment]
Sweet

**Comment by AlexDoesAThing11** [comment]
sex
